#!/usr/bin/env python3.10

from sys import argv
from os import system

def dev(todo:str)->None:
    match todo:
        case 'format':
            system("stylua . ; echo 'Project formatted!'")
        case _:
            raise BaseException('That is not a valid todo!')

def github(todo:str)->None:
    match todo:
        case 'publish':
            system("git push &> /dev/null; echo 'Project published!'")
        case _:
            raise BaseException('That is not a valid todo!')


def main(operation:str,todo:str)->None:
    match operation:
        case 'dev':
            dev(todo)
        case 'github':
            github(todo)
        case _:
            raise BaseException('That is not a valid operation!')


if __name__ =="__main__":
    try:
        main(argv[1],argv[2])
    except IndexError:
        print("You are missing parameters!")
