#!/usr/bin/env python3.10

"""
This is just a small imitation of the npm scripts property :)
"""

#  TODO: Pass this script to Lua

from os import system
from sys import argv


def dev(todo:str)->None:
    match todo:
        case 'format':
            system("stylua . ; echo 'Project formatted!'")
        case 'lint':
            system("luacheck .")
        case 'fix':
            system("./ultivim dev format && ./ultivim dev lint")
        case _:
            raise BaseException('That is not a valid todo!')

def github(todo:str)->None:
    match todo:
        case 'publish':
            system("git push &> /dev/null; echo 'Project published!'")
        case 'commit':
            system("git add . && git commit -m 'Automated commit 🤖'")
        case 'pack':
            system("./ultivim github commit && ./ultivim github publish")
        case _:
            raise BaseException('That is not a valid todo!')


def main(operation:str,todo:str)->None:
    match operation:
        case 'dev':
            dev(todo)
        case 'github':
            github(todo)
        case _:
            raise BaseException('That is not a valid operation!')


if __name__ =="__main__":
    try:
        main(argv[1],argv[2])
    except IndexError:
        print("You are missing parameters!")
